version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Battlesnake"
s3_prefix = "Battlesnake"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

